services:
  - type: web
    name: textbelt-open-source
    env: docker
    plan: free
    autoDeploy: true
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: REDIS_URL
        value: redis://red-d2nmi2i4d50c73b55n5g:6379
      - key: SMTP_HOST
        value: smtp.laposte.net
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: jean-marie.tremblay
      - key: SMTP_PASS
        value: vegve7-qogduv-zycGod
      - key: SMTP_FROM
        value: "sms@yourdomain.tld"
